def bystro_dengi(num):  # Юмористы, шутники))
    print(num, end='')


bystro_dengi(8)
bystro_dengi(8)
bystro_dengi(0)
bystro_dengi(0)
bystro_dengi(5)
bystro_dengi(5)
bystro_dengi(5)
bystro_dengi(3)
bystro_dengi(5)
bystro_dengi(3)
bystro_dengi(5)
